# Feature Extraction:
    
1. BOW

2. Ngram

3. TF-IDF

4. Onehot encoding

5. Word2vec

6. doc2vec


# BOW-Bag of words

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
text=['I have a little daughter','Mary had a little lamp','Twinkle twinkle little star'
 'The silence of lamps']
#Initialize the vector
vectorizer=CountVectorizer()
#transform
x=vectorizer.fit_transform(text)
#get feature names(words)
feature_names=vectorizer.get_feature_names_out()
#Display BOW-Matrix
print('Feature names:\n',feature_names)
print()
print('BOW Matrix:\n')
print(x.toarray())

Feature names:
 ['daughter' 'had' 'have' 'lamp' 'lamps' 'little' 'mary' 'of' 'silence'
 'starthe' 'twinkle']

BOW Matrix:

[[1 0 1 0 0 1 0 0 0 0 0]
 [0 1 0 1 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 1 1 1 2]]


# TF-IDF

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
text=['I have a little daughter','Mary had a little lamp','Twinkle twinkle little star'
 'The silence of lamps']
tfidf=TfidfVectorizer()
x_tfidf=tfidf.fit_transform(text)
features_names_tfidf=tfidf.get_feature_names_out()
print('Feature Names(TF-IDF):\n',features_names_tfidf)
print()
print('TF-IDF Matrix:\n',x_tfidf.toarray())

Feature Names(TF-IDF):
 ['daughter' 'had' 'have' 'lamp' 'lamps' 'little' 'mary' 'of' 'silence'
 'starthe' 'twinkle']

TF-IDF Matrix:
 [[0.65249088 0.         0.65249088 0.         0.         0.38537163
  0.         0.         0.         0.         0.        ]
 [0.         0.54645401 0.         0.54645401 0.         0.32274454
  0.54645401 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.34608857 0.20440549
  0.         0.34608857 0.34608857 0.34608857 0.69217714]]


In [5]:
import nltk
from nltk.tokenize import sent_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
text=input('Enter a statement:\n\t')

sent_token=sent_tokenize(text)
#print('Sentences:\n',sent_token)
for sent in sent_token:
    print(sent)
    print(len(sent))
 
print()

tfidf=TfidfVectorizer()
x_tfidf=tfidf.fit_transform(sent_token)
features_names_tfidf=tfidf.get_feature_names_out()
print('Feature Names(TF-IDF):\n',features_names_tfidf)
print()
print('TF-IDF Matrix:\n',x_tfidf.toarray())

Enter a statement:
	hello, welcome to the nlp day 2 session. Hope the session going well. Wanted to check that the session is understandable
hello, welcome to the nlp day 2 session.
40
Hope the session going well.
28
Wanted to check that the session is understandable
50

Feature Names(TF-IDF):
 ['check' 'day' 'going' 'hello' 'hope' 'is' 'nlp' 'session' 'that' 'the'
 'to' 'understandable' 'wanted' 'welcome' 'well']

TF-IDF Matrix:
 [[0.         0.43535684 0.         0.43535684 0.         0.
  0.43535684 0.25712876 0.         0.25712876 0.3311001  0.
  0.         0.43535684 0.        ]
 [0.         0.         0.52004008 0.         0.52004008 0.
  0.         0.30714405 0.         0.30714405 0.         0.
  0.         0.         0.52004008]
 [0.39916886 0.         0.         0.         0.         0.39916886
  0.         0.23575556 0.39916886 0.23575556 0.30357821 0.39916886
  0.39916886 0.         0.        ]]


# N-grams:

In [6]:
import nltk
from nltk import ngrams
text='g-grams are used in natural language processing'
tokens=nltk.word_tokenize(text)
#Generate bigrams
n=2
bigrams=list(ngrams(tokens,n))
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in bigrams:
    print(gram)

Original text:g-grams are used in natural language processing

Generated 2-grams:
('g-grams', 'are')
('are', 'used')
('used', 'in')
('in', 'natural')
('natural', 'language')
('language', 'processing')


In [7]:
import nltk
from nltk import ngrams
text='g-grams are used in natural language processing'
tokens=nltk.word_tokenize(text)
#Generate n-grams
n=3
ngrams=list(ngrams(tokens,n))
print(f"Original text:{text}")

print()
print(f"Generated {n}-grams:")
for gram in ngrams:
    print(gram)

Original text:g-grams are used in natural language processing

Generated 3-grams:
('g-grams', 'are', 'used')
('are', 'used', 'in')
('used', 'in', 'natural')
('in', 'natural', 'language')
('natural', 'language', 'processing')


In [8]:
import nltk
from nltk import ngrams
text='g-grams are used in natural language processing'
tokens=nltk.word_tokenize(text)
#Generate n-grams
n=4
ngrams=list(ngrams(tokens,n))
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in ngrams:
    print(gram)

Original text:g-grams are used in natural language processing

Generated 4-grams:
('g-grams', 'are', 'used', 'in')
('are', 'used', 'in', 'natural')
('used', 'in', 'natural', 'language')
('in', 'natural', 'language', 'processing')


In [9]:
#generate n-grams with list comprehension
n=2
text='g-grams are used in natural language processing'
tokens=nltk.word_tokenize(text)
ngrams=[tokens[i:i+n] for i in range(len(tokens)-n+1)]
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in ngrams:
    print(gram)


Original text:g-grams are used in natural language processing

Generated 2-grams:
['g-grams', 'are']
['are', 'used']
['used', 'in']
['in', 'natural']
['natural', 'language']
['language', 'processing']


In [10]:
#generate n-grams with list comprehension
n=3
text='g-grams are used in natural language processing'
tokens=nltk.word_tokenize(text)
ngrams=[tokens[i:i+n] for i in range(len(tokens)-n+1)]
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in ngrams:
    print(gram)

Original text:g-grams are used in natural language processing

Generated 3-grams:
['g-grams', 'are', 'used']
['are', 'used', 'in']
['used', 'in', 'natural']
['in', 'natural', 'language']
['natural', 'language', 'processing']


# onehot encoding:
    
Use for categorical data

converting text token into numeric form

steps:
1. Tokenization
2. Vocabulary creation
3. Encoding


In [11]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
text=['I have a little daughter','Mary had a little lamp','Twinkle twinkle little star','The silence of lamps']
#step 1- tokens
tokens=[word for sent in text for word in sent.lower().split()]
#step 2- vocabulary
vocabulary=list(set(tokens)) # unique words in the text
#initialize encoder
encoder=OneHotEncoder(categories=[vocabulary],sparse=False)

#Perform the one-hot encoding
one_hot_encoded=[]
for sent in text:
    sent_encoded=[]
    for word in sent.lower().split():
        word_index=vocabulary.index(word)
        word_vector=np.zeros(len(vocabulary))
        word_vector[word_index]=1
        sent_encoded.append(word_vector)
    one_hot_encoded.append(sent_encoded)
 
for sent in one_hot_encoded:
    print(sent)

[array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])]
[array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]), array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]
[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])]
[array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0.

In [12]:
sent[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
sent[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [14]:
len(sent)

4

In [15]:
type(sent)

list